services:
  airflow:
    build: .
    container_name: vehicleiq_airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: standalone